[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "requests>=2.32.3",
    "streamlit>=1.42.2",
    "twilio>=9.4.6",
    "uvicorn>=0.34.0",
]
